### ISSUE TITLE
Missing WWII Earth check

### ISSUE THREAD

**Issue by PTwr** [Game-fan-hoarder/Stellaris-flag-check#2]
For annoying **Outside Context** achievement player needs to find Earth during WWII, which requires it to start in Machine Age.

File save will need star named `NAME_Sol` with planet named `NAME_Sol_III`.

Nuked earth can be filtered out by checking for `planet_class="pc_continental"`.

Exact population required for WWII (machine age) Earth seems to change between patches, last month `num_sapient_pops=22` was correct value.

Because it will only last for few game years, it would be nice to list rough planet location.

For reference here's a horrible powershell script I clobbered out to find it: https://gist.github.com/PTwr/b28cf7a03aa276ef5d017fb81fed929e

**Comment by PTwr** [comment]
Aaaand done: https://github.com/Game-fan-hoarder/Stellaris-flag-check/pull/3
Getting star position would require some more `gamestate` parsing, but there are existing galaxy mappers which might be used instead.

**Comment by HOZHENWAI** [comment]
Thank you for your contribution, will do a release once i'm back.
